FROM node:10.8

RUN mkdir -p /home/node/app; \
    chown node -R /home/node; \
    npm install -g jsdoc jasmine

USER node

WORKDIR /home/node/app

ADD node/package.json  /home/node/app

RUN npm install

